import { Box } from "@opentui/core";

export const LOGO_WIDTH = 63;
export const LOGO_HEIGHT = 7;

// LOGO / HARNESS TEXT USING BOXES
export const harnessLogo = Box(
  { position: "absolute", top: 2, left: 50, width: LOGO_WIDTH, height: LOGO_HEIGHT },
  // H
  Box({
    position: "absolute",
    top: 0,
    left: 0,
    width: 1,
    height: 5,
    backgroundColor: "#333333",
  }),
  Box({
    position: "absolute",
    top: 0,
    left: 4,
    width: 1,
    height: 5,
    backgroundColor: "#333333",
  }),
  Box({
    position: "absolute",
    top: 2,
    left: 1,
    width: 3,
    height: 1,
    backgroundColor: "#333333",
  }),
  // A
  Box({
    position: "absolute",
    top: 0,
    left: 6,
    width: 1,
    height: 5,
    backgroundColor: "#333333",
  }),
  Box({
    position: "absolute",
    top: 0,
    left: 10,
    width: 1,
    height: 5,
    backgroundColor: "#333333",
  }),
  Box({
    position: "absolute",
    top: 0,
    left: 7,
    width: 3,
    height: 1,
    backgroundColor: "#333333",
  }),
  Box({
    position: "absolute",
    top: 2,
    left: 7,
    width: 3,
    height: 1,
    backgroundColor: "#333333",
  }),
  // R
  Box({
    position: "absolute",
    top: 0,
    left: 12,
    width: 1,
    height: 5,
    backgroundColor: "#333333",
  }),
  Box({
    position: "absolute",
    top: 0,
    left: 13,
    width: 3,
    height: 1,
    backgroundColor: "#333333",
  }),
  Box({
    position: "absolute",
    top: 0,
    left: 16,
    width: 1,
    height: 3,
    backgroundColor: "#333333",
  }),
  Box({
    position: "absolute",
    top: 2,
    left: 13,
    width: 3,
    height: 1,
    backgroundColor: "#333333",
  }),
  Box({
    position: "absolute",
    top: 3,
    left: 15,
    width: 1,
    height: 2,
    backgroundColor: "#333333",
  }),
  // N
  Box({
    position: "absolute",
    top: 0,
    left: 18,
    width: 1,
    height: 5,
    backgroundColor: "#333333",
  }),
  Box({
    position: "absolute",
    top: 0,
    left: 19,
    width: 2,
    height: 2,
    backgroundColor: "#333333",
  }),
  Box({
    position: "absolute",
    top: 2,
    left: 20,
    width: 2,
    height: 2,
    backgroundColor: "#333333",
  }),
  Box({
    position: "absolute",
    top: 0,
    left: 22,
    width: 1,
    height: 5,
    backgroundColor: "#333333",
  }),
  // E
  Box({
    position: "absolute",
    top: 0,
    left: 24,
    width: 1,
    height: 5,
    backgroundColor: "#333333",
  }),
  Box({
    position: "absolute",
    top: 0,
    left: 25,
    width: 3,
    height: 1,
    backgroundColor: "#333333",
  }),
  Box({
    position: "absolute",
    top: 2,
    left: 25,
    width: 2,
    height: 1,
    backgroundColor: "#333333",
  }),
  Box({
    position: "absolute",
    top: 4,
    left: 25,
    width: 3,
    height: 1,
    backgroundColor: "#333333",
  }),
  // S
  Box({
    position: "absolute",
    top: 0,
    left: 29,
    width: 4,
    height: 1,
    backgroundColor: "#333333",
  }),
  Box({
    position: "absolute",
    top: 0,
    left: 29,
    width: 1,
    height: 3,
    backgroundColor: "#333333",
  }),
  Box({
    position: "absolute",
    top: 2,
    left: 29,
    width: 4,
    height: 1,
    backgroundColor: "#333333",
  }),
  Box({
    position: "absolute",
    top: 2,
    left: 32,
    width: 1,
    height: 3,
    backgroundColor: "#333333",
  }),
  Box({
    position: "absolute",
    top: 4,
    left: 29,
    width: 4,
    height: 1,
    backgroundColor: "#333333",
  }),
  // S
  Box({
    position: "absolute",
    top: 0,
    left: 34,
    width: 4,
    height: 1,
    backgroundColor: "#333333",
  }),
  Box({
    position: "absolute",
    top: 0,
    left: 34,
    width: 1,
    height: 3,
    backgroundColor: "#333333",
  }),
  Box({
    position: "absolute",
    top: 2,
    left: 34,
    width: 4,
    height: 1,
    backgroundColor: "#333333",
  }),
  Box({
    position: "absolute",
    top: 2,
    left: 37,
    width: 1,
    height: 3,
    backgroundColor: "#333333",
  }),
  Box({
    position: "absolute",
    top: 4,
    left: 34,
    width: 4,
    height: 1,
    backgroundColor: "#333333",
  }),
  // -
  Box({
    position: "absolute",
    top: 2,
    left: 39,
    width: 4,
    height: 1,
    backgroundColor: "#333333",
  }),
  // C
  Box({
    position: "absolute",
    top: 0,
    left: 44,
    width: 4,
    height: 1,
    backgroundColor: "#f0cea4",
  }),
  Box({
    position: "absolute",
    top: 0,
    left: 44,
    width: 1,
    height: 5,
    backgroundColor: "#f0cea4",
  }),
  Box({
    position: "absolute",
    top: 4,
    left: 44,
    width: 4,
    height: 1,
    backgroundColor: "#f0cea4",
  }),
  // O
  Box({
    position: "absolute",
    top: 0,
    left: 49,
    width: 4,
    height: 1,
    backgroundColor: "#f0cea4",
  }),
  Box({
    position: "absolute",
    top: 4,
    left: 49,
    width: 4,
    height: 1,
    backgroundColor: "#f0cea4",
  }),
  Box({
    position: "absolute",
    top: 0,
    left: 49,
    width: 1,
    height: 5,
    backgroundColor: "#f0cea4",
  }),
  Box({
    position: "absolute",
    top: 0,
    left: 52,
    width: 1,
    height: 5,
    backgroundColor: "#f0cea4",
  }),
  // D
  Box({
    position: "absolute",
    top: 0,
    left: 54,
    width: 1,
    height: 5,
    backgroundColor: "#f0cea4",
  }),
  Box({
    position: "absolute",
    top: 0,
    left: 54,
    width: 3,
    height: 1,
    backgroundColor: "#f0cea4",
  }),
  Box({
    position: "absolute",
    top: 4,
    left: 54,
    width: 3,
    height: 1,
    backgroundColor: "#f0cea4",
  }),
  Box({
    position: "absolute",
    top: 1,
    left: 57,
    width: 1,
    height: 3,
    backgroundColor: "#f0cea4",
  }),
  // E
  Box({
    position: "absolute",
    top: 0,
    left: 59,
    width: 1,
    height: 5,
    backgroundColor: "#f0cea4",
  }),
  Box({
    position: "absolute",
    top: 0,
    left: 59,
    width: 4,
    height: 1,
    backgroundColor: "#f0cea4",
  }),
  Box({
    position: "absolute",
    top: 2,
    left: 59,
    width: 3,
    height: 1,
    backgroundColor: "#f0cea4",
  }),
  Box({
    position: "absolute",
    top: 4,
    left: 59,
    width: 4,
    height: 1,
    backgroundColor: "#f0cea4",
  }),
);
